name: Live-Infra CI
on:
  push: {}
jobs:
  build:
    name: Live Infra
    runs-on: ubuntu-latest
    env: 
      TFMODULE: ${{ github.workspace }}
      tf_version: 'latest'
      tg_version: 'latest'
    steps:
      - name: Checkout Git Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: autero1/action-terraform@v0.1.0
        with:
          terraform_version: 1.1.5
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.0.0
        with:
          terragrunt_version: 0.26.7
          
      - name: Terragrunt Validate
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_binary: 'terraform'
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.TFMODULE }}
          tf_actions_comment: true
          
      - name: Terragrunt Plan
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.TFMODULE }}
          tf_actions_comment: true

      - name: Terragrunt apply-all
        run: terragrunt apply-all --terragrunt-non-interactive
